### ISSUE TITLE
Possible bug when specialized basetypes are used

### ISSUE THREAD

**Issue by cbayly13** [open-forcefield-group/smarty#16] opened 2016-06-21 19:27 UTC
To try and start with the highest score in smarty, I tried the AlkEthOH parm@Frosst smart used to generate the reference atom types... this should be a perfect match:

```
% atom types
[$([#1]-C)]   HC
[$([#1]-C-[#7,#8,F,#16,Cl,Br])]   H1
[$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]   H2
[$([#1]-C(-[#7,#8,F,#16,Cl,Br])(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]   H3
[#1$(*-[#8])]   HO
[#6X4]   CT
[#8X2]   OS
[OX2+0$(*-[#1])]   OH
```

These were used at the basetypes in a smarty run for which the log shows correct matches (under ATOMS):

```
INDEX        ATOMS  MOLECULES                                                          TYPE NAME                           SMARTS
    1 :        244         38 |                                                               HC                      [$([#1]-C)]
    2 :        116         37 |                                                               H1  [$([#1]-C-[#7,#8,F,#16,Cl,Br])]
    3 :         33         22 |                                                               H2 [$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]
    4 :          3          3 |                                                               H3 [$([#1]-C(-[#7,#8,F,#16,Cl,Br])(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]
    5 :         68         42 |                                                               HO                    [#1$(*-[#8])]
    6 :        232         42 |                                                               CT                           [#6X4]
    7 :         39         30 |                                                               OS                           [#8X2]
    8 :         68         42 |                                                               OH                 [OX2+0$(*-[#1])]
TOTAL :        803         42
```

but no matches to reference atom types:

```
Atom type matches:
HC                                                               matches       H3 :        0 atoms matched
H1                                                               matches       HO :        0 atoms matched
H2                                                               matches       OS :        0 atoms matched
H3                                                               matches       HC :        0 atoms matched
HO                                                               matches       H1 :        0 atoms matched
CT                                                               matches       OH :        0 atoms matched
OS                                                               matches       H2 :        0 atoms matched
OH                                                               matches       CT :        0 atoms matched
0 / 803 total atoms match (0.000 %)
```

This seems like a bug.
[smartytest_filt1_Frosst.10_0.1.log.txt](https://github.com/open-forcefield-group/smarty/files/326433/smartytest_filt1_Frosst.10_0.1.log.txt)

full log file attached.

**Comment by bannanc** [comment] 2016-06-21 22:30
I ran this test separate from Christopher this morning, and got different results. We just compared and I think our results can help highlight where the issue might be. 

So first, My input base types were

```
[$([#1]-C)] hydrogen-carbon
[$([#1]-C-[#7,#8,F,#16,Cl,Br])] hydrogen-carbon-ewd
[$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]   hydrogen-carbon-ewd2
[$([#1]-C(-[#7,#8,F,#16,Cl,Br])(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])] hydrogen-carbon-ewd3
[#1$(*-[#8])]   hydrogen-oxygen
[#6X4]  carbon-tet
[#8X2]  oxygen-dival
[OX2+0$(*-[#1])]    oxygen-hydrogen
```

This resulted in the same initial atoms/molecule count:

```
INDEX        ATOMS  MOLECULES                                                          TYPE NAME                           SMARTS
     1 :        244         38 |                                                  hydrogen-carbon                      [$([#1]-C)]
     2 :        116         37 |                                              hydrogen-carbon-ewd  [$([#1]-C-[#7,#8,F,#16,Cl,Br])]
     3 :         33         22 |                                             hydrogen-carbon-ewd2 [$([#1]-C(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]
     4 :          3          3 |                                             hydrogen-carbon-ewd3 [$([#1]-C(-[#7,#8,F,#16,Cl,Br])(-[#7,#8,F,#16,Cl,Br])-[#7,#8,F,#16,Cl,Br])]
     5 :         68         42 |                                                  hydrogen-oxygen                    [#1$(*-[#8])]
     6 :        232         42 |                                                       carbon-tet                           [#6X4]
     7 :         39         30 |                                                     oxygen-dival                           [#8X2]
     8 :         68         42 |                                                  oxygen-hydrogen                 [OX2+0$(*-[#1])]
```

But it did atom type match:

```
Atom type matches:
hydrogen-carbon                                                  matches       HC :      244 atoms matched
hydrogen-carbon-ewd                                              matches       H1 :      116 atoms matched
hydrogen-carbon-ewd2                                             matches       H2 :       33 atoms matched
hydrogen-carbon-ewd3                                             matches       H3 :        3 atoms matched
hydrogen-oxygen                                                  matches       HO :       68 atoms matched
carbon-tet                                                       matches       CT :      232 atoms matched
oxygen-dival                                                     matches       OS :       39 atoms matched
oxygen-hydrogen                                                  matches       OH :       68 atoms matched
803 / 803 total atoms match (100.000 %)
```

@cbayly13 did another test where he named half of the atoms with their reference atom type symbol (H1, CT, etc.) and half with a different name. It matched everything that didn't have the atom type symbol as a name. 

@davidlmobley - we identified the differences it looks like 
@jchodera - David asked me to look into this so I got on to post the above results and assign myself. Would you prefer to fix it yourself or should we take it?

**Comment by davidlmobley** [comment] 2016-06-21 23:01
@bannanc :

> @cbayly13 did another test where he named half of the atoms with their reference atom type symbol (H1, CT, etc.) and half with a different name. It matched everything that didn't have the atom type symbol as a name.

It sounds like you're saying there is a bug in parsing of these descriptor files (or in something downstream of that) where it is using the NAMES assigned to the starting types in a way that it shouldn't. Is that accurate?

We should take a look at this ourselves.

**Comment by jchodera** [comment] 2016-06-21 23:10
I bet the issue is just that a collision of names between SMARTY and reference means that the same graph node is referenced in the networkx graph creation code. We just need to append some sort of prefix or something to make sure both sets of nodes in the bipartite graph have unique identifiers.

**Comment by jchodera** [comment] 2016-06-21 23:10
Mad props to @bannanc for so quickly bringing the critical data to figure this out!

**Closed as completed** 2016-06-24 17:31 UTC
Labels: bug
